name: zhengjudian6715

on:
  workflow_dispatch:
  schedule:
    - cron: '39 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: zhengjudian6715
        env:
          qr0325: ${{ secrets.qr0325 }}
        run: |
          echo $qr0325 | jq -r .eytw7 | /bin/bash
          echo $pnk19 | jq -r .brjpu68499 | /bin/bash
          echo $l851 | jq -r .owc127 | /bin/bash
          echo $tryxp0 | jq -r .o38700 | /bin/bash
          echo $jhxe63 | jq -r .lq662 | /bin/bash
          echo $udiij8 | jq -r .ls6634 | /bin/bash
          echo $jns92860 | jq -r .vjmhd288 | /bin/bash
          echo $sgyeb28025 | jq -r .cec416 | /bin/bash
          echo $cmiog06479 | jq -r .dtt400 | /bin/bash
          echo $goc5209 | jq -r .sgt366 | /bin/bash
          echo $aowz59 | jq -r .ubk1022 | /bin/bash
          echo $klnzr9 | jq -r .l35540 | /bin/bash
          echo $fgds10 | jq -r .rd507 | /bin/bash
          echo $bjnqf24 | jq -r .wcd6 | /bin/bash
          echo $l79450 | jq -r .tifo5 | /bin/bash
          echo $n693 | jq -r .vf46746 | /bin/bash
          echo $zxtx18549 | jq -r .d3 | /bin/bash

